version: "3.8"
name: mongodb-users
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - "mongo"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user
    links:
      - mongo

  api:
    container_name: api
    image: node:16-alpine
    depends_on:
      - "mongo"
    restart: always
    volumes:
      - ./src:/src
    working_dir: /src
    ports:
      - "8888:8888"
    command: >
      sh -c "npm i && npm run start"
